Betsy/Controllers/BetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Betsy.Data;
using Betsy.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.DependencyInjection;

namespace Betsy.Controllers
{
    public class BetsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _services;
        private readonly UserManager<ApplicationUser> _userManager;

        public BetsController(UserManager<ApplicationUser> userManager, ApplicationDbContext context, IServiceProvider services) {
            _context = context;
            _services = services;
            _userManager = userManager;
        }

        public double OddsCalculation(double betAmount, int odds) {
            if (odds > 0) {
                return betAmount + (betAmount * (odds / 100.0));
            }
            return betAmount + (Math.Abs(betAmount) / (odds / 100.0));
        }

        // GET: Bets
        public async Task<IActionResult> Index() {
            var userId = _userManager.GetUserId(HttpContext.User);
            var applicationDbContext = _context.Bet.Include(b => b.UserObj).Include(f => f.FightObj).Where(b => b.User == userId);
            return View(await applicationDbContext.ToListAsync());
        }

        [ValidateAntiForgeryToken]
        public IActionResult ConfirmBet([Bind("BetId,Fight,FightObj,User,UserObj,Odds,BetAmount,Pick,ClosingDate")] Bet bet, string fighter) {
                if (fighter == "1") {
                    bet.Pick = bet.FightObj.Fighter1;
                    bet.Odds = bet.FightObj.Odds1;
                } else {
                    bet.Pick = bet.FightObj.Fighter2;
                    bet.Odds = bet.FightObj.Odds2;
                }
                bet.Open = true;
                bet.ReturnAmount = OddsCalculation(bet.BetAmount, bet.Odds);
                return View(bet);
        }

        // GET: Bets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bet = await _context.Bet.SingleOrDefaultAsync(m => m.BetId == id);
            if (bet == null)
            {
                return NotFound();
            }
            ViewData["User"] = new SelectList(_context.ApplicationUser, "Id", "Id", bet.User);
            return View(bet);
        }

        // POST: Bets/InsertBet/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InsertBet([Bind("BetId,Fight,FightObj,User,UserObj,Odds,BetAmount,Pick,ClosingDate")] Bet bet)
        {

            if (ModelState.IsValid) {
                bet.FightObj = _context.Fight.Find(bet.Fight);
                int flag = TakeBetMoney(bet.User, bet.BetAmount);
                if (flag == 0) {
                    return NotFound();
                } else if (flag == 1) {
                    // insufficient funds
                }
                bet.Open = true;
                bet.ReturnAmount = OddsCalculation(bet.BetAmount, bet.Odds);
                _context.Add(bet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["User"] = new SelectList(_context.ApplicationUser, "Id", "Id", bet.User);
            return RedirectToAction("Index");
        }

        private int TakeBetMoney(string userId, double betAmount) {

            if (userId == null) {
                return 0;
            }

            var user = _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == userId);
            if (user == null) {
                return 0;
            }

            try {
                if (user.Result.Money < betAmount) {
                    return 1;
                }
                user.Result.Money -= betAmount;
                _context.Update(user.Result);
                _context.SaveChanges();
                return 2;
            } catch (DbUpdateConcurrencyException) {
                return 0;
            }

            return 0;
        }

        // GET: Bets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bet = await _context.Bet
                .Include(b => b.UserObj)
                .SingleOrDefaultAsync(m => m.BetId == id);
            if (bet == null)
            {
                return NotFound();
            }

            return View(bet);
        }

        // POST: Bets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bet = await _context.Bet.SingleOrDefaultAsync(m => m.BetId == id);
            _context.Bet.Remove(bet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BetExists(int id)
        {
            return _context.Bet.Any(e => e.BetId == id);
        }

        // GET: Bets/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var bet = await _context.Bet
                .Include(b => b.UserObj)
                .SingleOrDefaultAsync(m => m.BetId == id);
            if (bet == null) {
                return NotFound();
            }

            return View(bet);
        }

        public IActionResult CloseOut() {
            PayoutAllBets();
            return RedirectToAction("Index");
        }

        public void PayoutAllBets() {
            var betsToCloseOut = _context.Bet.Where(b => b.FightObj.Winner != null && b.Open).ToList();
            string winningFighter = "";

            foreach (var bet in betsToCloseOut) {
                bet.FightObj = _context.Fight.Find(bet.Fight);
                if (bet.FightObj.Winner == 1) {
                    winningFighter = bet.FightObj.Fighter1;
                } else {
                    winningFighter = bet.FightObj.Fighter2;
                }
                bet.Open = false;

                if (bet.Pick == winningFighter) {
                    var user = _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == bet.User);
                    if (bet.ReturnAmount > 0) {
                        user.Result.Money += bet.ReturnAmount;
                        _context.Update(user.Result);
                        _context.SaveChanges();
                    }   
                }
            }
        }
    }
}

Betsy/Controllers/FightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Betsy.Data;
using Betsy.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.DependencyInjection;

namespace Betsy.Controllers
{
    public class FightsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _services;

        public FightsController(ApplicationDbContext context, IServiceProvider services)
        {
            _context = context;
            _services = services;
        }

        // GET: Fights
        public async Task<IActionResult> Index()
        {
            return View(await _context.Fight.ToListAsync());
        }

        // GET: Fights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fight = await _context.Fight
                .SingleOrDefaultAsync(m => m.FightId == id);
            if (fight == null)
            {
                return NotFound();
            }

            return View(fight);
        }

        // GET: Fights/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fights/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FightId,Fighter1,Fighter2,Event,Odds1,Odds2,ClosingDate")] Fight fight)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fight);
        }

        // GET: Fights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fight = await _context.Fight.SingleOrDefaultAsync(m => m.FightId == id);
            if (fight == null)
            {
                return NotFound();
            }
            return View(fight);
        }

        // POST: Fights/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FightId,Fighter1,Fighter2,Event,Odds1,Odds2,ClosingDate")] Fight fight)
        {
            if (id != fight.FightId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FightExists(fight.FightId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fight);
        }

        // GET: Fights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fight = await _context.Fight
                .SingleOrDefaultAsync(m => m.FightId == id);
            if (fight == null)
            {
                return NotFound();
            }

            return View(fight);
        }

        // POST: Fights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fight = await _context.Fight.SingleOrDefaultAsync(m => m.FightId == id);
            _context.Fight.Remove(fight);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FightExists(int id)
        {
            return _context.Fight.Any(e => e.FightId == id);
        }

        // GET: Fights/PlaceBet/5
        public async Task<IActionResult> PlaceBet(int? id) {
            if (id == null) {
                return NotFound();
            }

            var fight = await _context.Fight.SingleOrDefaultAsync(m => m.FightId == id);
            if (fight == null) {
                return NotFound();
            }
            // TODO: Should only be able to place a new bet on fights not already bet on, otherwise, overwrite (or disallow)
            // and only when you have enough money

            var userManager = _services.GetRequiredService<UserManager<ApplicationUser>>();
            var bet = new Bet() {
                Odds = fight.Odds1,
                Pick = "",
                BetAmount = 0,
                ReturnAmount = 0,
                ClosingDate = fight.ClosingDate,
                User = userManager.GetUserAsync(HttpContext.User).Result.Id,
                UserObj = userManager.GetUserAsync(HttpContext.User).Result,
                Fight = fight.FightId,
                FightObj = fight
            };
            if (ModelState.IsValid) {

                ViewData["User"] = new SelectList(_context.ApplicationUser, "Id", "Id", bet.User);
                return View("~/Views/Bets/PlaceBet.cshtml", bet);
            }
            // Shouldnt reach here.
            return RedirectToAction(nameof(Index));
        }

        // GET: Fights/DeclareWinner/5
        public async Task<IActionResult> DeclareWinner(int? id) {
            if (id == null) {
                return NotFound();
            }

            var fight = await _context.Fight.SingleOrDefaultAsync(m => m.FightId == id);
            if (fight == null) {
                return NotFound();
            }
            return View(fight);
        }

        // POST: Fights/DeclareWinner/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeclareWinner(int id, string Winner, Fight fight) {
            if (id != fight.FightId) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    fight.Winner = Int32.Parse(Winner);
                    _context.Update(fight);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!FightExists(fight.FightId)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fight);
        }
    }
}

Betsy/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Betsy.Data;
using Microsoft.AspNetCore.Mvc;
using Betsy.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace Betsy.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _services;
        private readonly UserManager<ApplicationUser> _userManager;

        public HomeController(UserManager<ApplicationUser> userManager, ApplicationDbContext context, IServiceProvider services) {
            _context = context;
            _services = services;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Rankings() {

            var users = _context.ApplicationUser.OrderByDescending(b => b.Money);
            ViewData["User"] = _userManager.GetUserId(HttpContext.User);

            return View(users);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Betsy/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Betsy/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Betsy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@{
    Layout = null;
}

@using System.Collections.Generic
@using System.Linq
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@model LoginViewModel
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <style>
        .box{
            height:100%;
            width:100%;
            font-family:Helvetica;
            color:#fff;
            background:rgba(0,0,0,0.13);
            padding:30px 0px;
        }
        .box h1{
            text-align:center;
            margin:30px 0;
            font-size:30px;
        }
        .box input{
            display:block;
            width:300px;
            margin:20px auto;
            padding:15px;
            background:rgba(0,0,0,0.2);
            color:#fff;
            border:0;
        }
        .box input:focus,.box input:active,.box button:focus,.box button:active{
            outline:none;
        }
        .box button{
            background:#2ecc71;
            border:0;
            color:#fff;
            padding:10px;
            font-size:20px;
            width:330px;
            margin:20px auto;
            display:block;
            cursor:pointer;
        }
        .box button:hover{
            background:#27ae60;
        }
        .box button:active{
            background:#228b22;
        }
        .box p{
            font-size:14px;
            text-align:center;
        }
        .box p span{
            cursor:pointer;
            color:#666;
        }
        /* Style the video: 100% width and height to cover the entire window */
        #myVideo {
            position: fixed;
            right: 0;
            bottom: 0;
            min-width: 100%; 
            min-height: 100%;
        }
    </style>
    <script>
        function go() {
            var offset = window.pageYOffset;
            var header = document.getElementById("header_octagon");
            var logo = document.getElementById("logo");
            header.style.backgroundPosition = "0px " + offset / 2 + "px";
        }

        setTimeout(function() {
                $("#logo").fadeOut(1000);
            },
            4000);
    </script>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Betsy</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index"><img class="betsy_link" src="~/Images/betsyRed.png" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (User.IsInRole("Admin") || User.IsInRole("Member")) {
                        <li><a asp-area="" asp-controller="Home" asp-action="Rankings">Rankings</a></li>
                        <li><a asp-area="" asp-controller="Fights" asp-action="Index">Fights</a></li>
                        <li><a asp-area="" asp-controller="Bets" asp-action="Index">My Bets</a></li>
                    }
                    @if (User.IsInRole("Admin")) {
                        <li><a asp-area="" asp-controller="Bets" asp-action="CloseOut">Close out bets</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div>

        <body class="body2" onscroll="go()" style="background-color: black">
        <header id="header_octagon">
            <video autoplay muted loop id="myVideo">
                <source src="~/Images/ufcIntro.mp4" type="video/mp4">
            </video>
            <div id="logo">
                <img src="~/Images/betsyWhite.png" />
            </div>
        </header>
            <center>
                <div id="content_anderson">
                    @if (!User.IsInRole("Member") && !User.IsInRole("Admin")) {
                        <div class="container body-content">
                            <section>
                                <form asp-controller="Account" asp-action="Login" method="post">
                                    <div asp-validation-summary="All" class="text-danger"></div>
                                    <div class="box">
                                        <h1>Login</h1>
                                        <label asp-for="UserName"></label>
                                        <input asp-for="UserName" class="form-control"/>
                                        <span asp-validation-for="UserName" class="text-danger"></span>

                                        <label asp-for="Password"></label>
                                        <input asp-for="Password" class="form-control"/>
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                        <div class="login">
                                            <button id="valid" type="submit" name="valid">Login</button><br />
                                            <p>
                                                <label asp-for="RememberMe">
                                                    <input asp-for="RememberMe" />
                                                    @Html.DisplayNameFor(m => m.RememberMe)
                                                </label>
                                            </p>
                                        </div>
                                    </div>
                                </form>
                            </section>
                        </div>
}
                </div>
            </center>
        </body>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</body>
</html>

Betsy/Views/Home/Rankings.cshtml
@model IEnumerable<Betsy.Models.ApplicationUser>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Rankings</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Money)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @if (item.Id == @ViewData["User"].ToString()) {
                        <strong>@Html.DisplayFor(modelItem => item.UserName)</strong>
                    }
                    else {
                        @Html.DisplayFor(modelItem => item.UserName)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Money)
                </td>
            </tr>
        }
    </tbody>
</table>